---
- name: print server list 
  hosts: all

  tasks:
  - name: server host name & IP address
    debug:
      msg: The default IPv4 address of {{ ansible_fqdn }} is {{ ansible_default_ipv4.address }}
